=== yakushev85/GeneralJavaRepository/SEProjects/SILES/dtd/dialog.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT dialog (starts, points)>
<!ELEMENT starts (start+)>
<!ELEMENT start (point_id, regexp+)>
<!ELEMENT regexp (#PCDATA)>
<!ELEMENT point_id (#PCDATA)>
<!ELEMENT points (point+)>
<!ELEMENT point (id, reaction+, custom?, links?)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT reaction (#PCDATA)>
<!ELEMENT custom (class, input?)>
<!ELEMENT class (#PCDATA)>
<!ELEMENT input (#PCDATA)> 
<!ELEMENT links (link+)>
<!ELEMENT link (regexp+, point_id+)>

=== yakushev85/GeneralJavaRepository/SEProjects/SILES/dialog_hello.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE reactions SYSTEM "dtd/dialog.dtd">
<dialog>
	<starts>
		<start>
			<point_id>1</point_id>
			<regexp>^привет.*</regexp>
			<regexp>^здарова.*</regexp>
			<regexp>^здраствуй.*</regexp>
			<regexp>^добрый\s+день.*</regexp>
		</start>
	</starts>
	
	<points>
		<point>
			<id>1</id>
			<reaction>Привет! Как твои дела?</reaction>
			
			<links>
				<link>
					<regexp>^хорошо.*</regexp>
					<regexp>^отлично.*</regexp>
					<regexp>^чудесно.*</regexp>
					<regexp>^лучше\s+всех.*$</regexp>
					<point_id>2</point_id>
				</link>
				
				<link>
					<regexp>^не\s+очень.*</regexp>
					<regexp>^плохо.*</regexp>
					<regexp>^не\s+так\s+как\s+хотелось.*</regexp>
					<point_id>3</point_id>
				</link>
			</links>
		</point>
		
		<point>
			<id>2</id>
			<reaction>А у меня тоже всё отлично! Как там погодка на улице?</reaction>
			<reaction>А у меня дел особо нет поэтому всё отлично :) Как там погода на улице?</reaction>
			
			<links>
				<link>
					<regexp>^(погода\s+)?(отличная|хорошая|весенняя|cолнечная)\s+.*</regexp>
					<point_id>6</point_id>
				</link>
				
				<link>
					<regexp>^(погода\s+)?(плохая|дождливая|пасмурно|идёт)\s+.*</regexp>
					<point_id>7</point_id>
				</link>
				
			</links>
		</point>
		
		<point>
			<id>3</id>
			<reaction>А у меня всё хорошо. Что случилось поделись со мной?</reaction>
			<reaction>А у меня всё замечательно. Видимо что то испортило твои дела, поделись со мной?</reaction>
			
			<links>
				<link>
					<regexp>.*</regexp>
					<point_id>4</point_id>
					<point_id>5</point_id>
				</link>
			</links>
		</point>
		
		<point>
			<id>4</id>
			<reaction>Ну ты это крепись! ;)</reaction>
			
			<custom>
				<class>book</class>
				<input>добро.</input>
			</custom>
		</point>
		
		<point>
			<id>5</id>
			<reaction>Всё будет хорошо!</reaction>
			
			<custom>
				<class>book</class>
			</custom>
		</point>
		
		<point>
			<id>6</id>
			<reaction>Отлично!</reaction>
			<reaction>Супер :)</reaction>
		</point>

		<point>
			<id>7</id>
			<reaction>Как говорится у природы нет плохой погоды.</reaction>
			<reaction>Оу, не погуляешь видимо.</reaction>
		</point>		
	</points>
</dialog>
