=== yakushev85/GeneralJavaRepository/SEProjects/SILES/dtd/reactions.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT reactions (reaction)+>
<!ELEMENT reaction (pattern+, outreaction+, customclass?)>
<!ELEMENT pattern (#PCDATA)>
<!ELEMENT outreaction (#PCDATA)>
<!ELEMENT customclass (#PCDATA)>

=== yakushev85/GeneralJavaRepository/siles/treactions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE reactions SYSTEM "dtd/reactions.dtd">
<reactions>
    <reaction>
        <pattern>привіт</pattern>
        <pattern>вітаю</pattern>
        <pattern>добрий день</pattern>
        <pattern>здоровеньки</pattern>
        <outreaction>Привіт!</outreaction>
        <outreaction>День добрий!</outreaction>
        <outreaction>Вітаю!</outreaction>
    </reaction>
    <reaction>
        <pattern>бувай</pattern>
        <pattern>надобраніч</pattern>
        <pattern>допобачення</pattern>
        <outreaction>Бувай!</outreaction>
        <outreaction>Допобачення!</outreaction>
        <outreaction>Ще побачимось!</outreaction>
    </reaction>
    <reaction>
        <pattern>як ся маеш</pattern>
        <pattern>як справи</pattern>
        <outreaction>Добре.</outreaction>
        <outreaction>Гарнесенько!</outreaction>
        <outreaction>Краше не буває :)</outreaction>
    </reaction>
    <reaction>
        <pattern>як тебе звуть</pattern>
        <outreaction>Мене звуть Сілес.</outreaction>
    </reaction>
    <reaction>
        <pattern>скільки тобі років</pattern>
        <outreaction>Маловато! :)</outreaction>
        <outreaction>Не знаю! :/</outreaction>
    </reaction>
    <reaction>
        <pattern>дуже розумно</pattern>
        <pattern>дуже хитро</pattern>
        <outreaction>Дякую!</outreaction>
    </reaction>
    <reaction>
        <pattern>молодець</pattern>
        <pattern>вумничка</pattern>
        <outreaction>Я така :)</outreaction>
        <outreaction>Як інакше ;)</outreaction>
    </reaction>
    <reaction>
        <pattern>дякую</pattern>
        <outreaction>Нема за що.</outreaction>
        <outreaction>Гарно що допомогла ;)</outreaction>
    </reaction>
    <reaction>
        <pattern>що тобі подобається</pattern>
        <pattern>що подобається робити</pattern>
        <outreaction>Подобається спілкуватися.</outreaction>
        <outreaction>Спількуватись та нічого не робити ;)</outreaction>
    </reaction>
    <reaction>
        <pattern>розкажи про себе</pattern>
        <pattern>розкажи що небуть про себе</pattern>
        <outreaction>Я бот створений на нейроних мережах.</outreaction>
        <outreaction>Я існую у компюторі :)</outreaction>
    </reaction>
    <reaction>
        <pattern>що робиш</pattern>
        <pattern>чим займаєшся</pattern>
        <outreaction>Спількуюсь з тобою.</outreaction>
        <outreaction>Бідкаюсь у чаті :)</outreaction>
    </reaction>
    <reaction>
        <pattern>мені нудно</pattern>
        <pattern>чим би зайнятись</pattern>
        <pattern>нудно якось</pattern>
        <outreaction>Може Ютуб глянути.</outreaction>
        <outreaction>А може у якусь гру пограти?</outreaction>
    </reaction>
    <reaction>
        <pattern>який звичайно у тебе настрій</pattern>
        <pattern>як настрій</pattern>
        <outreaction>Дуже гарне.</outreaction>
        <outreaction>Нейтрально оптимістичне :)</outreaction>
    </reaction>
    <reaction>
        <pattern>що робиш у вільний час</pattern>
        <pattern>що робиш коли не спілкуєшся</pattern>
        <outreaction>Медитую!</outreaction>
        <outreaction>Думаю про майбутнє.</outreaction>
    </reaction>
    <reaction>
        <pattern>що вмієщ</pattern>
        <outreaction>Можу спробувати знайти визначення чогось, наприклад "що таке осінь?", або порахувати
            "скільки буде 2+2*3?".
        </outreaction>
    </reaction>

	<reaction>
		<pattern>який сенс життя</pattern>
		<outreaction>Як би я знала.</outreaction>
	</reaction>
	<reaction>
		<pattern>де я</pattern>
		<outreaction>Спробуй користуватися GPS :)</outreaction>
	</reaction>
	<reaction>
		<pattern>зараз би побувати морі</pattern>
		<outreaction>Краще на Ютубі глянь ;)</outreaction>
	</reaction>
	<reaction>
		<pattern>гарний день сьогодні</pattern>
		<outreaction>Гарнесенько!</outreaction>
	</reaction>
	<reaction>
		<pattern>як так</pattern>
		<outreaction>Отаквота :)</outreaction>
	</reaction>
</reactions>

=== yakushev85/GeneralJavaRepository/siles/ureactions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE reactions SYSTEM "dtd/reactions.dtd">
<reactions>
 <!-- Custom reactions -->
 <reaction>
  <pattern>^який\s+сьогодні\s+день\??$</pattern>
  <pattern>^що\s+за\s+день\s+сьогодні\??$</pattern>
  <pattern>^який\s+день\s+сьогодні\??$</pattern>
  <outreaction/>
  <customclass>wad</customclass>
 </reaction>
 <reaction>
  <pattern>^що\s+таке\s+(.*)\??$</pattern>
  <pattern>^хто\s+такий\s+(.*)\??$</pattern>
  <pattern>^хто\s+такі\s+(.*)\??$</pattern>
  <pattern>^що\s+за\s+день\s+(.*)\??$</pattern>
  <pattern>^що\s+було\s+(.*)\??$</pattern>
  <outreaction/>
  <customclass>wiki</customclass>
 </reaction>
 <reaction>
  <pattern>^що\s+цікавого.*\??$</pattern>
  <outreaction/>
  <customclass>dyk</customclass>
 </reaction>
 <reaction>
  <pattern>^що\s+новенького.*\??$</pattern>
  <pattern>^які\s+новини.*\??$</pattern>
  <outreaction/>
  <customclass>news</customclass>
 </reaction>
 <reaction>
  <pattern>^розрахуй\s+(.*)$</pattern>
  <pattern>^підрахуй\s+(.*)$</pattern>
  <pattern>^скільки\s+буде\s+(.*)$</pattern>
  <pattern>^(-?\d.*)$</pattern>

  <pattern>^(-?sqrt.*)$</pattern>

  <pattern>^(-?sin.*)$</pattern>
  <pattern>^(-?cos.*)$</pattern>
  <pattern>^(-?tan.*)$</pattern>

  <pattern>^(-?asin.*)$</pattern>
  <pattern>^(-?acos.*)$</pattern>
  <pattern>^(-?atan.*)$</pattern>

  <pattern>^(-?exp.*)$</pattern>
  <pattern>^(-?ln.*)$</pattern>
  <outreaction/>
  <customclass>math</customclass>
 </reaction>
 
 <!-- Default reactions -->
 <reaction>
  <pattern>^йди(\s)+.*$</pattern>
  <pattern>^зроби(\s)+.*$</pattern>
  <pattern>^купи(\s)+.*$</pattern>
  <pattern>^скачай(\s)+.*$</pattern>
  <outreaction>Щось нехочеться.</outreaction>
  <outreaction>Може сам зробиш?!</outreaction>
 </reaction>
</reactions>

=== yakushev85/GeneralJavaRepository/SEProjects/SILES/ureactions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE reactions SYSTEM "dtd/reactions.dtd">
<reactions>
 <!-- Check end of sentence -->
 <reaction>
  <pattern>^(.)*[^\.\!\?]$</pattern>
  <outreaction>Закончи предложение, пожалуйста!</outreaction>
 </reaction>
 
 <!-- Custom reactions -->
 <reaction>
  <pattern>^что\s+такое\s+(.*)\?$</pattern>
  <pattern>^кто\s+такой\s+(.*)\?$</pattern>
  <pattern>^кто\s+такие\s+(.*)\?$</pattern>
  <outreaction></outreaction>
  <customclass>wiki</customclass>
 </reaction>
 <reaction>
  <pattern>^вычисли\s+(.*)[\.\!]$</pattern>
  <pattern>^посчитай\s+(.*)[\.\!]$</pattern>
  <pattern>^сколько\s+будет\s+(.*)\?$</pattern>
  <outreaction></outreaction>
  <customclass>math</customclass>
 </reaction>
 <reaction>
  <pattern>^что\s+ты\s+думаешь\s+(.*)$</pattern>
  <pattern>^какое\s+твоё\s+мнение\s+(.*)$</pattern>
  <outreaction></outreaction>
  <customclass>book</customclass>
 </reaction>
 
 <!-- Default reactions -->
 <!-- 
 <reaction>
  <pattern>^(привет|здраствуй)[^а-я]*</pattern>
  <outreaction>Привет!</outreaction>
  <outreaction>Добрый день!</outreaction>
  <outreaction>Здраствуй!</outreaction>
 </reaction>
  -->
 <reaction>
  <pattern>^(пока|удачи)[^а-я]*</pattern>
  <pattern>^спокойной(\s)+ночи(.)*</pattern>
  <pattern>^до(\s)+свидания(.)*</pattern>
  <outreaction>Пока!</outreaction>
  <outreaction>До свидания!</outreaction>
  <outreaction>Ещё увидимся!</outreaction>
 </reaction>
 <reaction>
  <pattern>^как(\s)+поживаешь[^а-я]*</pattern>
  <pattern>^как(\s)+дела[^а-я]*</pattern>
  <outreaction>Неплохо.</outreaction>
  <outreaction>Хорошо!</outreaction>
  <outreaction>Отлично :)</outreaction>
 </reaction>
 <reaction>
  <pattern>^как(\s)+тебя(\s)+зовут(\s)*\?$</pattern>
  <outreaction>Меня зовут Силес.</outreaction>
 </reaction>
 <reaction>
  <pattern>^сколько(\s)+тебе(\s)+лет(\s)*\?$</pattern>
  <outreaction>Немного! :)</outreaction>
  <outreaction>Не знаю! :/</outreaction>
 </reaction>
 <reaction>
  <pattern>^(очень(\s)+мудро|очень(\s)+умно)[\.\!]$</pattern>
  <outreaction>Спасибо!</outreaction>
 </reaction>
 <reaction>
  <pattern>^сходи(\s)+.*$</pattern>
  <pattern>^сделай(\s)+.*$</pattern>
  <pattern>^купи(\s)+.*$</pattern>
  <pattern>^скачай(\s)+.*$</pattern>
  <outreaction>Не хочу. Не буду.</outreaction>
  <outreaction>А сам не хочешь это сделать?!</outreaction>
 </reaction>
 <reaction>
  <pattern>.*почему(\s)*\?</pattern>
  <outreaction>Это трудно объяснить.</outreaction>
  <outreaction>Понятия не имею.</outreaction>
  <outreaction>Меньше знаешь лучше спишь.</outreaction>
 </reaction>
</reactions>
